# Pandas Intro

## DataFrames

Pandas is a module for working with tables. The most important data structure in Pandas is the DataFrame, which you can think of as being similar to an Excel table, or an SQL table. Let's import the Pandas module and create a dataframe:

In [1]:
import pandas as pd

df = pd.DataFrame({'col_1': [6,7,11], 'col_2': ['a', 'b', 'c']})
print(df)

   col_1 col_2
0      6     a
1      7     b
2     11     c


We've created a dataframe called ``df``. It contains two variables (columns) and three observations (rows). In this case, we created the DataFrame using a dictionary, where the keys in the dictionary become the column names in the DataFrame, and the values in the dictionary become the data within each column.

Note that DataFrames always have an index column, shown in the above output as the leftmost column (in this case the index contains the values 0, 1, and 2). If you do not specify an index when you create a DataFrame, Pandas will create an auto-incrementing index for you.

Now let's create a DataFrame that looks a little more like real data:

In [2]:
import numpy as np

data = {
    'name': ['Jeff', 'Julia', 'Ronda', 'Dinesh', 'Susan'],
    'height': [183, 176, 187, 157, 1],
    'weight': [69, 73, np.nan, 77, 82],
    'gender': ['m', 'f', 'f', 'm', 'f']
}

df = pd.DataFrame(data)
print(df)

     name  height  weight gender
0    Jeff     183    69.0      m
1   Julia     176    73.0      f
2   Ronda     187     NaN      f
3  Dinesh     157    77.0      m
4   Susan       1    82.0      f


Here we have five observations across four variables. Note that one of the weight observations is a missing value, which in Pandas is conventionally represented by the NaN value ("Not a Number").

The above DataFrame ``df`` was created by converting a Python Dictionary object into a Pandas DataFrame object. Note that you can also specify the columns and observations (rows) separately when creating a DataFrame:

In [3]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
],dtype='int64')
print(a)
print(type(a))

# Create DataFrame using a Numpy array and specifying column names
df_fromarray = pd.DataFrame(a, columns=['x', 'y', 'z'])
print(df_fromarray)
print(type(df_fromarray))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
   x  y  z
0  1  2  3
1  4  5  6
2  7  8  9
<class 'pandas.core.frame.DataFrame'>


Now create another dataframe that contains identical columns and observations to ``df_fromarray``, but use a dictionary rather than an array to create it:

In [4]:
d =  {
    'x': [1,2,3],
    'y': [1,2,3],
    'z': [1,2,3],
}



# Create DataFrame using a dictionary
df_fromdict = pd.DataFrame(d)# Write your code here...

print(type(df_fromdict.iloc[0]['x']))
print(type(df_fromarray.iloc[0]['x']))
assert df_fromarray.equals(df_fromdict), 'The DataFrames are not identical'

<class 'numpy.int64'>
<class 'numpy.int64'>


AssertionError: The DataFrames are not identical

Note that the ``.equals()`` method in the code above is used to check if two DataFrames are identical.

## The Series class, and selecting DataFrame columns

Another important data structure in Pandas is the Series, which is like a single column of an Excel table. You can also think of them as being very similar to Array data structure in Numpy, although with a bit more flexible.

Let's create a Series:

In [5]:
s = pd.Series([39, 43, 25])
print(s)

0    39
1    43
2    25
dtype: int64


Note that if we select a particular column of a DataFrame, it returns a Series object, not a DataFrame object:

In [6]:
df['name']

0      Jeff
1     Julia
2     Ronda
3    Dinesh
4     Susan
Name: name, dtype: object

In [7]:
type(df['name'])
print(type(df['name']))
print(type(s))
assert df['name'].equals(s), 'The DataFrames are not identical'

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


AssertionError: The DataFrames are not identical

However, if we select multiple columns, a DataFrame is returned, not a Series:

In [8]:
df[['name', 'height']]

name  height
0    Jeff     183
1   Julia     176
2   Ronda     187
3  Dinesh     157
4   Susan       1

In [9]:
type(df[['name', 'height']])

pandas.core.frame.DataFrame

Note that we can also select a column of a DataFrame using slightly different syntax: ``df.col_name``, rather than ``df['col_name']``:

In [10]:
df.name

0      Jeff
1     Julia
2     Ronda
3    Dinesh
4     Susan
Name: name, dtype: object

You can use either syntax, but note that the ``.`` syntax is slightly more limited, because it requires that the column name contain only letters, numbers, and underscores; i.e. no whitespace or other special characters.

## Some useful DataFrame attributes and methods

DataFrames have a number of useful attributes and methods. Some that you might find useful are:

In [11]:
# provides information on dataframe variables (columns), numbers of observations (rows), and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    5 non-null      object 
 1   height  5 non-null      int64  
 2   weight  4 non-null      float64
 3   gender  5 non-null      object 
dtypes: float64(1), int64(1), object(2)
memory usage: 288.0+ bytes


In [12]:
# Gives the shape of a DataFrame
df.shape

(5, 4)

In [13]:
# Gives the column names of the DataFrame
df.columns

Index(['name', 'height', 'weight', 'gender'], dtype='object')

In [14]:
# Gives the index of the DataFrame
df.index

RangeIndex(start=0, stop=5, step=1)

The ``.unique()`` Series method gives the unique values in a DataFrame column (Series):

In [15]:
df['gender'].unique()

array(['m', 'f'], dtype=object)

In [16]:
df['height'].unique()

array([183, 176, 187, 157,   1], dtype=int64)

The ``.value_counts()`` Series method can be used to count instances of each unique value in a DataFrame column (Series). For example, we can use it to count instances of each unique value in the ``'gender'`` column of ``df``:

In [17]:
# Count instances of each unique value in a column
df['gender'].value_counts()

f    3
m    2
Name: gender, dtype: int64

In [18]:
df['height'].value_counts()

183    1
157    1
187    1
1      1
176    1
Name: height, dtype: int64

In [19]:
# Simple descriptive statistics for each column (of numeric or object data type)
df.describe()

height     weight
count    5.000000   4.000000
mean   140.800000  75.250000
std     78.994937   5.560276
min      1.000000  69.000000
25%    157.000000  72.000000
50%    176.000000  75.000000
75%    183.000000  78.250000
max    187.000000  82.000000

The descriptive statistics included in the ``.describe()`` DataFrame method are:

- **count:** count of the number of non-NA/null observations,
- **mean:** mean of the values,
- **std:** standard deviation of the observations,
- **min:** minimum of the values,
- **max:** maximum of the values,
- the 25th, 50th (median), and 75th percentiles.

## Selecting rows

We can select particular rows in a DataFrame which satisfy a given condition, using either of the following syntax options:

- ``df[condition]``
- ``df.loc[condition]``

For example:

In [20]:
df.loc[df['name'] == 'Julia']

name  height  weight gender
1  Julia     176    73.0      f

In [21]:
df[df['name'] == 'Julia']

name  height  weight gender
1  Julia     176    73.0      f

This returns a new DataFrame of any rows that match the condition within ``[...]``. So depending on the search condition, we can also return multiple rows:

In [22]:
df[df['gender'] == 'f']

name  height  weight gender
1  Julia     176    73.0      f
2  Ronda     187     NaN      f
4  Susan       1    82.0      f

Multiple conditions must be contained by brackets ``(...)`` and separated by ``&`` for the AND operator, ``|`` for the OR operator, etc...

Write a line in the cell below that selects rows for women that are > 180cm.

In [23]:
df[(df['gender'] == 'f') | (df['height'] > 180)]

name  height  weight gender
0   Jeff     183    69.0      m
1  Julia     176    73.0      f
2  Ronda     187     NaN      f
4  Susan       1    82.0      f

Now change the above to an OR operator (``|``) rather than an AND operator (``&``), and re-run the above cell. It should now select all rows where gender is female or height is > 180cm.

Now try selecting all data other than Ronda's data using the NOT EQUALS operator (``!=``):

In [24]:
df[(df['gender'] == 'f') & (df['height'] > 180)]

name  height  weight gender
2  Ronda     187     NaN      f

Note that we can also assign any returned DataFrame to a new variable:

In [25]:
j_rows = df[df['name'].str.startswith('J')]
print(j_rows)

    name  height  weight gender
0   Jeff     183    69.0      m
1  Julia     176    73.0      f


It is useful to understand how Pandas identifies and returns the above rows. The query ``df[df['gender'] == 'f']`` actually contains a couple of different steps. First, the condition ``df['gender'] == 'f'`` grabs the "gender" column and returns the *indices* of all rows that have the value "f" in that column:

In [26]:
df['gender'] == 'f'

0    False
1     True
2     True
3    False
4     True
Name: gender, dtype: bool

This returns a Series of Boolean values (True of False) that identify whether each row satisfies the condition. This Series is then used to return all rows where the condition is True:

In [27]:
df[df['gender'] == 'f']

name  height  weight gender
1  Julia     176    73.0      f
2  Ronda     187     NaN      f
4  Susan       1    82.0      f

This means that if we provide a list of Bool values, we would get the same result:

In [28]:
df[[False, True, True, False, True]]

name  height  weight gender
1  Julia     176    73.0      f
2  Ronda     187     NaN      f
4  Susan       1    82.0      f

## Saving and loading DataFrames

Pandas has inbuilt functions that make it easy to save dataframes and load datasets of different formats into dataframes. One of the most common data formats is the comma-separated variable (CSV) format, where each row is an observation, and each variable in that row is separated by a comma. We can save our ``df`` DataFrame to disk as a CSV file:

In [29]:
file_name = 'height_weight.csv'
df.to_csv(file_name,index=False)

We can then load the same DataFrame, assigning it to a different variable name:

In [30]:
data = pd.read_csv(file_name)
print(data)

     name  height  weight gender
0    Jeff     183    69.0      m
1   Julia     176    73.0      f
2   Ronda     187     NaN      f
3  Dinesh     157    77.0      m
4   Susan       1    82.0      f


Note that this has an extra column ``'Unnamed: 0'``. This was loaded because the ``.to_csv()`` method will automatically save the DataFrame's index to the CSV file as a new column, in addition to all other data.

To prevent this, we need to specify ``index=False`` as an option when calling the ``.to_csv()`` method. Add the ``index=False`` option to the ``.to_csv()`` call above and re-run that cell. Then re-run the subsequent cell containing the ``.read_csv()`` call. It should now load a dataframe without the ``'Unnamed: 0'`` column.

## Exercise 1

Create a DataFrame called ``volumes`` with:
- a single column called ``'radius (m)'``,
- 20 rows, each with a radius value randomly chosen from between the bounding values 3.0 and 10.0. You can use Numpy's``np.random.uniform(low=a, high=b, size=(n,))`` function, which returns an array of ``n`` randomly generated numbers drawn from a uniform distribution between the numbers ``a`` and ``b``.

Create a new column called ``'sphere_vol (m^3)'`` containing the corresponding volume of a sphere for each of the radius values. The formula for calculating the volume of a sphere is:

$V = {4 \over 3} \pi r^3$

Note that the value for $\pi$ is available in Numpy using the ``np.pi`` variable.

Now print only the rows where the volume is > $30 m^3$.

Save the ``volumes`` DataFrame to the location ``'../data/volumes.csv'``. Then load the data into a new DataFrame called ``vol`` and check that it is equivalent to the ``volumes`` DataFrame. If the DataFrames are not equivalent, one possibility is that floating point rounding errors have created slightly different floats in the new dataframe. One way to check this is by rounding all float values in each dataframe to, say, 5 decimal places using the ``df.round()`` method, and then performing the comparison between the rounded dataframes.

In [31]:
a=np.random.uniform(low=3.0,high=10.0,size=(20,))
#volumes=pd.DataFrame('radius (m):')
print(a)
volume = pd.DataFrame(a, columns=['radius (m)'])
print(volume)
volume['sphere volume']=volume['radius (m)']**3*np.pi*4/3
print(volume)
volume[volume['sphere volume']>3000]
#volume.to_csv['volumes.csv']
volume.to_csv('volumes.csv')

[4.61359056 5.30285911 8.87213865 3.82455004 5.77120453 8.47448178
 7.55489292 9.69618677 9.74709781 8.7712341  7.53118669 7.18558935
 3.07634168 4.56209382 3.92999448 5.76040816 6.80679389 4.06763786
 3.38166467 6.04050474]
    radius (m)
0     4.613591
1     5.302859
2     8.872139
3     3.824550
4     5.771205
5     8.474482
6     7.554893
7     9.696187
8     9.747098
9     8.771234
10    7.531187
11    7.185589
12    3.076342
13    4.562094
14    3.929994
15    5.760408
16    6.806794
17    4.067638
18    3.381665
19    6.040505
    radius (m)  sphere volume
0     4.613591     411.344559
1     5.302859     624.624298
2     8.872139    2925.321278
3     3.824550     234.330949
4     5.771205     805.170780
5     8.474482    2549.341761
6     7.554893    1806.232069
7     9.696187    3818.488850
8     9.747098    3878.953577
9     8.771234    2826.641407
10    7.531187    1789.282235
11    7.185589    1554.088657
12    3.076342     121.952953
13    4.562094     397.723495
14    3.92